services:

  stateless-webserver:
    build:
      context: ./express-app
    restart: always
    environment:
      - NODE_ENV=production
      # - CONTAINER_ID=${CONTAINER_NAME}
      # - CONTAINER_INDEX=${SCALE_INDEX}
    # container_name: express_app_${SCALE_INDEX}  # Replace with an identifier
    ports:
      - "3000"
    deploy:
      replicas: 3

  nginx:
    image: nginx:latest
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stateless-webserver
    ports:
      - "8080:8080"

# networks: 
#   default: 
#     # external: true
#     name: iot-server-network